const {test}=require('node:test');const assert=require('node:assert/strict');
const fs=require('node:fs');const vm=require('node:vm');const os=require('node:os');const path=require('node:path');const {spawnSync}=require('node:child_process');
const source=fs.readFileSync('app/src/main/assets/session-store.js','utf8');
const fixture={access_token:'fixture-access',refresh_token:'fixture-refresh',expires_at:Math.floor(Date.now()/1000)+3600,user:{id:'user-1'}};
const credentials={kind:'saved-login-v1',email:'fixture@example.test',password:'fixture-only',userId:'user-1'};
function setup(options={}){
 let saved=options.session?JSON.stringify(fixture):null,login=options.empty?null:{...credentials},pending=null,result=null;
 const listeners=new Map(),data=new Map();const ok=value=>JSON.stringify({ok:true,value});
 const bridge={read:()=>ok(saved),write:v=>{saved=v;return ok(null)},clear:()=>{saved=null;return ok(null)}};
 const loginBridge={status:()=>ok({available:true,enabled:!!login}),save:(v,id)=>{pending={action:'save',id,value:JSON.parse(v)};return ok(null)},use:id=>{pending={action:'use',id};return ok(null)},cancel:()=>{pending=null;result=null;return ok(null)},forget:()=>{login=null;pending=null;result=null;return ok(null)},take:id=>{if(!result||result.id!==id)return JSON.stringify({ok:false,error:'No authenticated result'});const value=result.value;result=null;return ok(JSON.stringify(value))}};
 const window={location:{origin:'https://appassets.androidplatform.net'},CleanThingsNativeSession:bridge,CleanThingsNativeLogin:loginBridge,addEventListener:(n,cb)=>listeners.set(n,cb),removeEventListener:(n,cb)=>{if(listeners.get(n)===cb)listeners.delete(n)}};
 const localStorage={getItem:k=>data.get(k)||null,removeItem:k=>data.delete(k)};
 const context={window,localStorage,setTimeout,clearTimeout,AbortController};vm.createContext(context);vm.runInContext(source,context);
 function reply(result,id=pending?.id){listeners.get('cleanthings:biometric-result')?.({detail:{id,result}})}
 return {store:window.CleanThingsSessionStore,context,window,data,loginBridge,get pending(){return pending},get login(){return login},reply,complete(){const p=pending;pending=null;if(p.action==='save')login=p.value;else result={id:p.id,value:{...login}};reply({ok:true},p.id)},fail(){const p=pending;pending=null;reply({ok:false,error:'Cancelled'},p.id)},get listeners(){return listeners}};
}
function withBackend(h,fetcher){h.window.CLEAN_THINGS_CONFIG={supabaseUrl:'https://fixture.supabase.co',supabasePublishableKey:'sb_publishable_fixture_only'};h.context.fetch=fetcher;vm.runInContext(fs.readFileSync('app/src/main/assets/backend.js','utf8'),h.context);return h.window.CleanThingsBackend;}
const response=(payload,status=200)=>({ok:status<400,status,text:async()=>JSON.stringify(payload)});
const tick=()=>new Promise(r=>setImmediate(r));
test('BIO-01 saved credentials do not gate active sessions or app startup',()=>{const h=setup({session:true});assert.equal(h.store.read().user.id,'user-1');assert.equal(h.pending,null);assert.equal(h.store.lock,undefined);});
test('BIO-02 logout removes tokens but retains saved login; native proof does not itself create a session',async()=>{const h=setup({session:true});h.store.clear();assert.equal(h.store.read(),null);assert.ok(h.login);const p=h.store.useSavedLogin();h.reply({ok:true},'wrong-id');assert.ok(h.pending);h.complete();assert.equal((await p).password,credentials.password);assert.equal(h.store.read(),null);assert.equal(h.listeners.size,0);});
test('BIO-03 forged event cannot retrieve credentials; one-use result required',async()=>{const h=setup();const p=h.store.useSavedLogin();h.reply({ok:true});await assert.rejects(p,/authenticated/);h.store.cancelSavedLogin();assert.equal(h.store.read(),null);});
test('BIO-04 cancelled replacement preserves previous saved login and current session',async()=>{const h=setup({session:true});const p=h.store.saveLogin({...credentials,email:'replacement@example.test'});await assert.rejects(h.store.useSavedLogin(),/already open/);h.fail();await assert.rejects(p,/Cancelled/);assert.equal(h.login.email,credentials.email);assert.ok(h.store.read());});
test('BIO-05 logout cancels pending retrieval and rejects late success while retaining saved credentials',async()=>{const h=setup();const p=h.store.useSavedLogin();const id=h.pending.id;h.store.clear();await assert.rejects(p,/cancelled/);h.reply({ok:true},id);assert.equal(h.store.read(),null);assert.ok(h.login);});
test('BIO-06 forget removes saved credentials without ending active account session',()=>{const h=setup({session:true});h.store.forgetSavedLogin();assert.equal(h.login,null);assert.ok(h.store.read());assert.equal(h.store.status().biometric.enabled,false);assert.equal(h.data.size,0);});
test('BIO-07 actual Java envelope authenticates wrapping, payload, key identity and refreshed data',()=>{
 const out=fs.mkdtempSync(path.join(os.tmpdir(),'ct-biometric-'));
 try {
  const compile=spawnSync('java',['-m','jdk.compiler/com.sun.tools.javac.Main','-d',out,'app/src/main/java/gy/cleanthings/app/SessionCipher.java','app/src/main/java/gy/cleanthings/app/BiometricEnvelope.java','tests/java/BiometricEnvelopeTest.java','tests/java/BiometricAuthOrderTest.java'],{encoding:'utf8'});assert.equal(compile.status,0,compile.stderr);
  const run=spawnSync('java',['-cp',out,'gy.cleanthings.app.BiometricEnvelopeTest'],{encoding:'utf8'});assert.equal(run.status,0,run.stderr);assert.match(run.stdout,/passed/);
  const order=spawnSync('java',['-cp',out,'gy.cleanthings.app.BiometricAuthOrderTest'],{encoding:'utf8'});assert.equal(order.status,0,order.stderr);assert.match(order.stdout,/regression reproduced/);
 }finally{fs.rmSync(out,{recursive:true,force:true})}
});

test('BIO-08 native credential vault is separate, strong auth-per-use; no app lock or background timer',()=>{
 const vault=fs.readFileSync('app/src/main/java/gy/cleanthings/app/SavedLoginVault.java','utf8');const main=fs.readFileSync('app/src/main/java/gy/cleanthings/app/MainActivity.java','utf8');
 assert.match(vault,/setUserAuthenticationParameters\(0,KeyProperties.AUTH_BIOMETRIC_STRONG\)/);assert.match(vault,/setInvalidatedByBiometricEnrollment\(true\)/);assert.match(vault,/sessions.currentUserId\(\)/);assert.match(vault,/UUID.randomUUID/);assert.match(vault,/expected!=generation/);assert.match(vault,/getNoBackupFilesDir/);assert.match(main,/CleanThingsNativeLogin/);assert.doesNotMatch(main,/stoppedAt|FLAG_SECURE|elapsedRealtime|recreate\(/);
 const start=vault.indexOf('private synchronized void prompt'),callback=vault.indexOf('@Override public void onAuthenticationSucceeded',start);
 assert.doesNotMatch(vault.slice(start,callback),/\.updateAAD\s*\(|\.doFinal\s*\(/);assert.match(vault.slice(callback),/BiometricEnvelope.unwrap\(cipher/);
 const session=fs.readFileSync('app/src/main/java/gy/cleanthings/app/SessionVault.java','utf8');assert.doesNotMatch(session,/saved-login/);
});
test('BIO-09 biometric login makes fresh server password grant and checks identity before accepting session',async()=>{const h=setup();let requests=0;const api=withBackend(h,async(url,opt)=>{if(url.includes('/logout'))return response({});requests++;assert.match(url,/grant_type=password/);assert.deepEqual(JSON.parse(opt.body),{email:credentials.email,password:credentials.password});return response(fixture)});const p=api.signInWithBiometrics();assert.equal(requests,0);h.complete();await p;assert.equal(requests,1);assert.equal(api.session().user.id,'user-1');await api.signOut();assert.ok(h.login);assert.equal(api.session(),null);});
test('BIO-10 successful password sign-in precedes optional saving; cancel save still signs in',async()=>{const h=setup({empty:true});const api=withBackend(h,async()=>response(fixture));const p=api.signIn(credentials.email,credentials.password,{saveLogin:true});await tick();assert.ok(api.session());assert.equal(h.pending.action,'save');h.fail();assert.match((await p).savedLoginError,/Cancelled/);assert.ok(api.session());assert.equal(h.login,null);});
test('BIO-11 password sign-in without consent never saves; incorrect password never opens prompt',async()=>{const h=setup({empty:true});let status=200;const api=withBackend(h,async()=>response(status===200?fixture:{msg:'Invalid credentials'},status));await api.signIn(credentials.email,credentials.password);assert.equal(h.pending,null);await api.signOut();status=400;await assert.rejects(api.signIn(credentials.email,'wrong',{saveLogin:true}));assert.equal(h.pending,null);assert.equal(h.login,null);});
test('BIO-12 logout during network authentication prevents late biometric session restoration',async()=>{const h=setup();let finish;const api=withBackend(h,async(url)=>url.includes('grant_type=password')?new Promise(r=>finish=()=>r(response(fixture))):response({}));const p=api.signInWithBiometrics();h.complete();await tick();await api.signOut();finish();await assert.rejects(p,/cancelled/);assert.equal(api.session(),null);assert.ok(h.login);});
test('BIO-13 wrong account and changed password fail closed; saved login can be forgotten',async()=>{const h=setup();let status=200;const api=withBackend(h,async()=>response(status===200?{...fixture,user:{id:'different'}}:{error_code:'invalid_credentials',msg:'Invalid credentials'},status));let p=api.signInWithBiometrics();h.complete();await assert.rejects(p,/no longer matches/);assert.equal(api.session(),null);status=400;p=api.signInWithBiometrics();h.complete();await assert.rejects(p);assert.equal(api.session(),null);api.forgetSavedLogin();assert.equal(h.login,null);});
test('BIO-14 opt-in saves verified account and ordinary refresh is independent from biometric protection',async()=>{const h=setup({empty:true});const api=withBackend(h,async()=>response(fixture));const p=api.signIn(credentials.email,credentials.password,{saveLogin:true});await tick();h.complete();await p;assert.equal(h.login.userId,'user-1');h.store.write({...fixture,access_token:'rotated'});assert.equal(h.store.read().access_token,'rotated');assert.equal(h.pending,null);});
