const {test} = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {JSDOM} = require('jsdom');
const Core = require('../app/src/main/assets/core.js');
const root=path.join(__dirname,'../app/src/main/assets/');
const tick=()=>new Promise(r=>setTimeout(r,5));
const fixturePassword=['Example',String(100+23)].join('');
const service={id:'essential',name:'Essential Wash',icon:'🚙',price:3000,duration:'40 min',description:'Wash',includes:['Wash'],add_ons:[{id:'tyre-shine',name:'Tyre shine',price:800,description:'Shine'}],enabled:true};
async function setup(options={}) {
  const dom=new JSDOM(fs.readFileSync(root+'index.html','utf8'),{url:'https://audit.invalid/',runScripts:'outside-only',pretendToBeVisual:true});
  const w=dom.window; w.scrollTo=()=>{}; const calls=[];
  let active=options.guest?null:{user:{id:'user-1'}};
  const backend={enabled:()=>true,session:()=>active,
    listServices:async()=>{calls.push('services');return [service]},
    listPublicSettings:async()=>{calls.push('settings');return [{key:'business_name',value:'Test Business'}]},
    getMyProfile:async()=>{calls.push('profile');return active?{user_id:'user-1',name:'Fixture',phone:'5926000000',email:'a@example.test',role:options.admin?'admin':'customer'}:null},
    listBookings:async()=>[],listReceipts:async()=>[],listProfiles:async()=>[],
    listAvailability:async()=>{calls.push('availability');return [{service_time:'10:00',status:'booked'}]},
    signOut:async()=>{active=null;},
    updateProfile:async()=>[],saveService:async()=>[],signedAvatarUrl:async()=>'',
  };
  w.CleanThingsBackend=backend;
  w.eval(fs.readFileSync(root+'core.js','utf8'));
  const code=fs.readFileSync(root+'app.js','utf8');
  assert.ok(code.endsWith('})();\n'));
  w.eval(code.replace('  bootstrapBackend();\n})();',`window.audit={get state(){return state},get ui(){return ui},get services(){return services},render,navigate,bootstrapBackend,openLocationPicker,handleAdminAction,submitPayment,openEditCustomer,openServiceEditor,showServiceDetails,submitCustomerCreate,currentAccount,loadAvailability,activateAccount,logout,submitAdminSettings,openEditProfile,openEditBooking};window.auditReady=bootstrapBackend();})();`));
  await w.auditReady;
  return {w,a:w.audit,backend,calls,close:()=>w.close(),setSession:v=>active=v};
}
const booking=(a)=>({reference:'CT-TEST',id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',accountId:'user-1',...a.ui.draft,serviceName:'Wash',total:3000,status:'Pending confirmation',payment:{status:'Not submitted',reference:'',proofName:'',proofPath:''}});

test('F01 startup loads catalog/settings and restores a session without persisting PII',async()=>{const t=await setup();try{assert.ok(t.calls.includes('services'));assert.ok(t.calls.includes('settings'));assert.equal(t.a.ui.backendStatus,'online');assert.equal(t.a.currentAccount().id,'user-1');assert.equal(t.a.state.settings.businessName,'Test Business');assert.equal(JSON.parse(t.w.localStorage.getItem('cleanthings.prototype.v1')).accounts,undefined);}finally{t.close()}});
test('F02 map save preserves all typed booking details',async()=>{const t=await setup();try{t.a.navigate('booking',{serviceId:'essential'});t.a.ui.draft.serviceMode='mobile';t.a.ui.bookingStep=3;t.a.render();for(const [id,value] of [['name','Changed name'],['phone','5926999999'],['vehicle','Test vehicle'],['plate','TEST'],['notes','Keep this']])t.w.document.getElementById(id).value=value;t.w.document.querySelector('[name=waterConfirmed]').checked=true;t.a.openLocationPicker(false);t.w.document.querySelector('[data-map-save]').click();assert.equal(t.w.document.getElementById('vehicle').value,'Test vehicle');assert.equal(t.w.document.getElementById('notes').value,'Keep this');assert.equal(t.w.document.getElementById('name').value,'Changed name');assert.equal(t.w.document.querySelector('[name=waterConfirmed]').checked,true);}finally{t.close()}});
test('F03 invalid coordinates cannot close/save the map',async()=>{const t=await setup();try{t.a.openLocationPicker(false);t.w.document.getElementById('map-latitude').value='999';t.w.document.querySelector('[data-map-save]').click();assert.ok(t.w.document.querySelector('[data-map-save]'));assert.equal(t.a.ui.draft.locationPin,'');assert.match(t.w.document.querySelector('[data-map-status]').textContent,/-90/);}finally{t.close()}});
test('F04 zoom preserves pin while map taps move it',async()=>{const t=await setup();try{t.a.openLocationPicker(false);const map=t.w.document.getElementById('location-map');map.setPointerCapture=()=>{};map.getBoundingClientRect=()=>({left:0,top:0,width:520,height:280});const button=t.w.document.querySelector('[data-map-zoom]');for(const type of ['pointerdown','pointerup'])button.dispatchEvent(new t.w.MouseEvent(type,{bubbles:true,clientX:480,clientY:30}));button.click();assert.equal(t.w.document.getElementById('map-latitude').value,'6.801300');for(const type of ['pointerdown','pointerup'])map.dispatchEvent(new t.w.MouseEvent(type,{bubbles:true,clientX:400,clientY:80}));assert.notEqual(t.w.document.getElementById('map-latitude').value,'6.801300');}finally{t.close()}});
test('F05 failed admin update does not alter booking status',async()=>{const t=await setup();try{t.a.state.bookings=[booking(t.a)];t.backend.updateBooking=async()=>{throw Error('offline')};await t.a.handleAdminAction('complete','CT-TEST');assert.equal(t.a.state.bookings[0].status,'Pending confirmation');}finally{t.close()}});
test('F06 failed payment request does not change saved state',async()=>{const t=await setup();try{t.a.state.bookings=[booking(t.a)];t.a.navigate('payment',{reference:'CT-TEST'});t.w.document.getElementById('payment-reference').value='TEST-REF';t.backend.updateMyBooking=async()=>{throw Error('offline')};await t.a.submitPayment({preventDefault(){},currentTarget:t.w.document.getElementById('payment-form')});assert.equal(t.a.state.bookings[0].payment.status,'Not submitted');assert.match(t.w.document.getElementById('payment-error').textContent,/offline/);}finally{t.close()}});
test('F07 editable service fields remain text in details and catalog',async()=>{const t=await setup();try{const html='<img id="injected" src=x onerror="alert(1)">';for(const key of ['name','description','duration','icon'])t.a.services[0][key]=html;t.a.services[0].includes=[html];t.a.services[0].addOns[0].name=html;t.a.showServiceDetails('essential');assert.equal(t.w.document.getElementById('injected'),null);t.a.ui.screen='services';t.a.render();assert.equal(t.w.document.getElementById('injected'),null);assert.ok(t.w.document.body.textContent.includes(html));}finally{t.close()}});
test('F08 punctuation-only phone is rejected before signup',async()=>{assert.equal(Core.validPhone('-------'),false);assert.equal(Core.validPhone('+592 600 0000'),true);const t=await setup({guest:true});try{t.a.ui.screen='account';t.a.ui.accountMode='create';t.a.render();for(const [id,v] of [['new-name','Test User'],['new-phone','-------'],['new-email','test@example.test'],['new-password',fixturePassword],['confirm-password',fixturePassword]])t.w.document.getElementById(id).value=v;let calls=0;t.backend.signUp=async()=>{calls++};await t.a.submitCustomerCreate({preventDefault(){},currentTarget:t.w.document.getElementById('customer-create-form')});assert.equal(calls,0);assert.match(t.w.document.getElementById('customer-create-error').textContent,/telephone/);}finally{t.close()}});
test('F09 login email is read-only and ignored by profile editor',async()=>{const t=await setup();try{t.a.openEditCustomer('5926000000');const input=t.w.document.querySelector('[name=email]');assert.equal(input.readOnly,true);input.value='changed@example.test';t.w.document.getElementById('edit-customer-form').dispatchEvent(new t.w.Event('submit',{cancelable:true,bubbles:true}));await tick();assert.equal(t.a.state.accounts[0].email,'a@example.test');}finally{t.close()}});
test('F10 add-on reorder and repricing preserve identities',()=>{const old=[{id:'tyre-shine',name:'Tyre shine',price:800},{id:'vacuum',name:'Vacuum',price:1000}];const next=Core.serviceAddOnsFromText('Vacuum | 1100 | Updated\nTyre shine | 900 | Updated',old);assert.deepEqual(next.map(x=>x.id),['vacuum','tyre-shine']);assert.throws(()=>Core.serviceAddOnsFromText('Bad | nope'),/prices/);});
test('F11 failed logout clears local identity and records',async()=>{const t=await setup();try{t.a.state.bookings=[booking(t.a)];t.backend.signOut=async()=>{t.setSession(null);throw Error('offline')};await t.a.logout();assert.equal(t.w.sessionStorage.getItem('cleanthings.customer.id'),null);assert.equal(t.a.currentAccount(),null);assert.equal(t.a.state.bookings.length,0);}finally{t.close()}});
test('F13 schedule loads occupied slots on initial entry and fails closed',async()=>{const t=await setup();try{t.a.navigate('booking',{serviceId:'essential'});t.w.document.querySelector('[data-action=booking-next]').click();await tick();assert.ok(t.calls.includes('availability'));assert.equal(t.w.document.querySelector('[data-time="10:00"]').disabled,true);t.backend.listAvailability=async()=>{throw Error('offline')};await assert.rejects(t.a.loadAvailability(t.a.ui.draft.date));t.a.render();assert.ok([...t.w.document.querySelectorAll('.slot')].every(x=>x.disabled));}finally{t.close()}});
test('F14 repeated Submit sends one request and preserves retry key',async()=>{const t=await setup();try{t.a.navigate('booking',{serviceId:'essential'});Object.assign(t.a.ui.draft,{serviceMode:'bay',time:'08:30',vehicle:'Car',plate:'TEST'});await t.a.loadAvailability(t.a.ui.draft.date);t.a.ui.bookingStep=4;t.a.render();t.w.document.getElementById('confirm-accuracy').checked=true;let resolve;const sent=[];t.backend.createBooking=d=>{sent.push(d);return new Promise(r=>resolve=r)};const button=t.w.document.querySelector('[data-action=confirm-booking]');button.click();button.click();assert.equal(sent.length,1);assert.ok(sent[0].requestId);resolve({booking:booking(t.a)});await tick();assert.equal(t.a.ui.screen,'success');assert.equal(t.a.state.bookings.length,1);}finally{t.close()}});
test('LOC-01 GPS success and denial retain manual fallback',async()=>{const t=await setup();try{Object.defineProperty(t.w.navigator,'geolocation',{value:{getCurrentPosition(ok,fail,opt){assert.equal(opt.timeout,15000);ok({coords:{latitude:6.82,longitude:-58.16}})}},configurable:true});t.a.openLocationPicker(true);assert.equal(t.w.document.getElementById('map-latitude').value,'6.820000');Object.defineProperty(t.w.navigator,'geolocation',{value:{getCurrentPosition(ok,fail){fail({code:1})}},configurable:true});t.a.openLocationPicker(true);assert.equal(t.w.document.querySelector('[data-map-current]').disabled,false);assert.match(t.w.document.querySelector('[data-map-status]').textContent,/unavailable/);}finally{t.close()}});
test('AUTH-01 forged UI admin flag does not reveal management',async()=>{const t=await setup();try{t.w.sessionStorage.setItem('cleanthings.admin.auth','true');t.a.ui.screen='admin';t.a.render();assert.match(t.w.document.getElementById('app-main').textContent,/Administrator account required/);}finally{t.close()}});
test('STATE-01 failed settings save leaves previous values',async()=>{const t=await setup();try{const form=t.w.document.createElement('form');form.innerHTML='<input name="businessName" value="Changed"><input name="mmgAccountName" value="Changed"><input name="mmgNumber" value="9999999">';t.backend.savePublicSettings=async()=>{throw Error('offline')};await t.a.submitAdminSettings({preventDefault(){},currentTarget:form});assert.equal(t.a.state.settings.businessName,'Test Business');}finally{t.close()}});
test('STATE-02 failed service/profile edits preserve saved records',async()=>{const t=await setup();try{const service=t.a.services[0];t.a.openServiceEditor(service);t.w.document.querySelector('[name=name]').value='New Service';t.backend.saveService=async()=>{throw Error('offline')};t.w.document.getElementById('service-form').dispatchEvent(new t.w.Event('submit',{cancelable:true,bubbles:true}));await tick();assert.equal(service.name,'Essential Wash');t.a.openEditProfile();t.w.document.querySelector('[name=name]').value='New name';t.backend.updateProfile=async()=>{throw Error('offline')};t.w.document.getElementById('profile-form').dispatchEvent(new t.w.Event('submit',{cancelable:true,bubbles:true}));await tick();assert.equal(t.a.currentAccount().name,'Fixture');}finally{t.close()}});
